### ISSUE TITLE
filemanager.php is missing

### ISSUE THREAD

**Issue by Fraddy** [matjazpotocnik/ProcessFileManager#1]
filemanager.php seems to be missing from the filemananger directory.

**Comment by matjazpotocnik** [comment]
Is the module working for you, even without filemanager.php?

**Comment by Fraddy** [comment]
I plan to use it standalone and I grabbed filemanager.php from the older -dev release. It only shows "File Manager" with the 3 circle spinner. The content table with 2 columns is empty.
I configured rootDir and tried to set fmWebPath. No errors are logged. I will have to dig into the code...

**Comment by matjazpotocnik** [comment]
This module is for ProcessWire and is not intended to be used standalone, thus filemanager.php (and some other files) is not needed. You may use original filemanager from Gerd Tentler at http://www.gerd-tentler.de/tools/filemanager/

**Comment by Fraddy** [comment]
OK, thanks.
